### PR TITLE
nanopore error handling at irma failure for empty input

### PR DESCRIPTION
**Pull request by kristinelacek**
Failure point was at Irma, actually, from what I found. Simple fix, still retains sample in all figures

### CODE REVIEW

**Comment by nbx0** [comment]
closing instead. discussed adding `|| touch IRMA/SC2.{wildcards.barcode}.fin`

**Comment by kristinelacek** [comment]
wait no we need both

**Comment by kristinelacek** [comment]
SC2 had this at rule 1 and was failing at irma

**Comment by nbx0** [comment]
maybe because `docker exec` still exits `0`?

**Pull request closed without merging**
